import MuiThemeContext from "@/context/MuiThemeContext";
import "./globals.css";
import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";

const inter = Instrument_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  fallback: ["system-ui", "arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MuiThemeContext>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </MuiThemeContext>
  );
}
